spring.application.name=VK_testing

grpc.server.port=9090

tarantool.host=localhost
tarantool.port=3301
tarantool.username=guest
tarantool.password=
tarantool.connect-timeout=PT5S
tarantool.request-timeout=PT5S
